version: "3"

services:
  mongodb_migrate:
    image: mongo:4
    restart: always
    container_name: mongodb_migrate
    environment:
      MONGO_INITDB_ROOT_USERNAME: leafium
      MONGO_INITDB_ROOT_PASSWORD: leafium
      MONGO_INITDB_DATABASE: leafium-db
    ports:
      - '27017:27017'

  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_replica
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: leafium
      MONGO_INITDB_ROOT_PASSWORD: leafium
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27018:27018'

volumes:
  mongo-data:
